# Generated by Django 5.2.7 on 2025-10-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Título')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor')),
                ('ano', models.IntegerField(verbose_name='Ano de publicação')),
                ('editora', models.CharField(max_length=255, null=True, verbose_name='Editora')),
                ('edicao', models.IntegerField(verbose_name='Edição')),
            ],
        ),
    ]
