# Generated by Django 5.2.7 on 2025-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=1, verbose_name='Qtde disponível'),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_total',
            field=models.PositiveIntegerField(default=1, verbose_name='Qtde total'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Editora'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='livros', to='biblioteca.categoria', verbose_name='Categorias'),
        ),
    ]
